//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Brief Pain Inventory Information</summary>
	[PublishedModel("briefPainInventoryInformation")]
	public partial class BriefPainInventoryInformation : Master
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "briefPainInventoryInformation";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BriefPainInventoryInformation, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public BriefPainInventoryInformation(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Enjoyment of life
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("enjoymentOfLife")]
		public string EnjoymentOfLife => this.Value<string>("enjoymentOfLife");

		///<summary>
		/// General activity
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("generalActivity")]
		public string GeneralActivity => this.Value<string>("generalActivity");

		///<summary>
		/// In the last week, how much relief have pain treatments or medications provided? Please circle the one percentage that best shows how much relief you have received
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("inTheLastWeekHowMuchReliefHavePainTreatmentsOrMedicationsProvidedPleaseCircleTheOnePercentageThatBestShowsHowMuchReliefYouHaveReceived")]
		public string InTheLastWeekHowMuchReliefHavePainTreatmentsOrMedicationsProvidedPleaseCircleTheOnePercentageThatBestShowsHowMuchReliefYouHaveReceived => this.Value<string>("inTheLastWeekHowMuchReliefHavePainTreatmentsOrMedicationsProvidedPleaseCircleTheOnePercentageThatBestShowsHowMuchReliefYouHaveReceived");

		///<summary>
		/// Mood
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("mood")]
		public string Mood => this.Value<string>("mood");

		///<summary>
		/// Normal work: (includes both outside the home and housework)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("normalWork")]
		public string NormalWork => this.Value<string>("normalWork");

		///<summary>
		/// Patient Date Of Birth
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("patientDateOfBirth")]
		public DateTime PatientDateOfBirth => this.Value<DateTime>("patientDateOfBirth");

		///<summary>
		/// Patient Full Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("patientFullName")]
		public string PatientFullName => this.Value<string>("patientFullName");

		///<summary>
		/// Patient Surname
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("patientSurname")]
		public string PatientSurname => this.Value<string>("patientSurname");

		///<summary>
		/// Please rate your pain by selecting the one number that best describes your pain at its least in the last week
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("pleaseRateYourPainBySelectingTheOneNumberThatBestDescribesYourPainAtItsLeastInTheLastWeek")]
		public string PleaseRateYourPainBySelectingTheOneNumberThatBestDescribesYourPainAtItsLeastInTheLastWeek => this.Value<string>("pleaseRateYourPainBySelectingTheOneNumberThatBestDescribesYourPainAtItsLeastInTheLastWeek");

		///<summary>
		/// Please rate your pain by selecting the one number that best describes your pain at its worst in the last week
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("pleaseRateYourPainBySelectingTheOneNumberThatBestDescribesYourPainAtItsWorstInTheLastWeek")]
		public string PleaseRateYourPainBySelectingTheOneNumberThatBestDescribesYourPainAtItsWorstInTheLastWeek => this.Value<string>("pleaseRateYourPainBySelectingTheOneNumberThatBestDescribesYourPainAtItsWorstInTheLastWeek");

		///<summary>
		/// Please rate your pain by selecting the one number that best describes your pain on average
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("pleaseRateYourPainBySelectingTheOneNumberThatBestDescribesYourPainOnAverage")]
		public string PleaseRateYourPainBySelectingTheOneNumberThatBestDescribesYourPainOnAverage => this.Value<string>("pleaseRateYourPainBySelectingTheOneNumberThatBestDescribesYourPainOnAverage");

		///<summary>
		/// Please rate your pain by selecting the one number that tells how much pain you have right now
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("pleaseRateYourPainBySelectingTheOneNumberThatTellsHowMuchPainYouHaveRightNow")]
		public string PleaseRateYourPainBySelectingTheOneNumberThatTellsHowMuchPainYouHaveRightNow => this.Value<string>("pleaseRateYourPainBySelectingTheOneNumberThatTellsHowMuchPainYouHaveRightNow");

		///<summary>
		/// Relations with other people
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("relationsWithOtherPeople")]
		public string RelationsWithOtherPeople => this.Value<string>("relationsWithOtherPeople");

		///<summary>
		/// Sleep
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("sleep")]
		public string Sleep => this.Value<string>("sleep");

		///<summary>
		/// Walking ability
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("walkingAbility")]
		public string WalkingAbility => this.Value<string>("walkingAbility");

		///<summary>
		/// What treatments or medications are you receiving for yourpain?
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("whatTreatmentsOrMedicationsAreYouReceivingForYourpain")]
		public string WhatTreatmentsOrMedicationsAreYouReceivingForYourpain => this.Value<string>("whatTreatmentsOrMedicationsAreYouReceivingForYourpain");
	}
}
