//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Contact Us</summary>
	[PublishedModel("contactUs")]
	public partial class ContactUs : Master, IBanner
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "contactUs";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContactUs, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public ContactUs(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Contact Us Email Subject
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("contactUsEmailSubject")]
		public string ContactUsEmailSubject => this.Value<string>("contactUsEmailSubject");

		///<summary>
		/// Contact Us Email Template
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("contactUsEmailTemplate")]
		public IHtmlString ContactUsEmailTemplate => this.Value<IHtmlString>("contactUsEmailTemplate");

		///<summary>
		/// Disease Placeholder Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("diseasePlaceholderText")]
		public string DiseasePlaceholderText => this.Value<string>("diseasePlaceholderText");

		///<summary>
		/// Disease Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("diseaseText")]
		public string DiseaseText => this.Value<string>("diseaseText");

		///<summary>
		/// Email Placeholder Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("emailPlaceholderText")]
		public string EmailPlaceholderText => this.Value<string>("emailPlaceholderText");

		///<summary>
		/// Email Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("emailText")]
		public string EmailText => this.Value<string>("emailText");

		///<summary>
		/// Map
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("map")]
		public string Map => this.Value<string>("map");

		///<summary>
		/// Message Placeholder Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("messagePlaceholderText")]
		public string MessagePlaceholderText => this.Value<string>("messagePlaceholderText");

		///<summary>
		/// Message Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("messageText")]
		public string MessageText => this.Value<string>("messageText");

		///<summary>
		/// Name Placeholder Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("namePlaceholderText")]
		public string NamePlaceholderText => this.Value<string>("namePlaceholderText");

		///<summary>
		/// Name Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("nameText")]
		public string NameText => this.Value<string>("nameText");

		///<summary>
		/// Phone Number Placeholder Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("phoneNumberPlaceholderText")]
		public string PhoneNumberPlaceholderText => this.Value<string>("phoneNumberPlaceholderText");

		///<summary>
		/// Phone Number Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("phoneNumberText")]
		public string PhoneNumberText => this.Value<string>("phoneNumberText");

		///<summary>
		/// Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("sendYourRequestHeading")]
		public string SendYourRequestHeading => this.Value<string>("sendYourRequestHeading");

		///<summary>
		/// Submit Button Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("submitButtonText")]
		public string SubmitButtonText => this.Value<string>("submitButtonText");

		///<summary>
		/// Banner Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("bannerDescription")]
		public IHtmlString BannerDescription => Banner.GetBannerDescription(this);

		///<summary>
		/// Banner heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("bannerHeading")]
		public string BannerHeading => Banner.GetBannerHeading(this);

		///<summary>
		/// Banner Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("bannerImage")]
		public IPublishedContent BannerImage => Banner.GetBannerImage(this);
	}
}
