//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Depression Anxiety Stress Score Information</summary>
	[PublishedModel("depressionAnxietyStressScoreInformation")]
	public partial class DepressionAnxietyStressScoreInformation : Master
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "depressionAnxietyStressScoreInformation";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<DepressionAnxietyStressScoreInformation, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public DepressionAnxietyStressScoreInformation(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// I couldn't seem to experience any positive feeling at all
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("iCouldnTSeemToExperienceAnyPositiveFeelingAtAll")]
		public string ICouldnTseemToExperienceAnyPositiveFeelingAtAll => this.Value<string>("iCouldnTSeemToExperienceAnyPositiveFeelingAtAll");

		///<summary>
		/// I experienced breathing difficulty: (eg, excessively rapid breathing, breathlessness in the absence of physical exertion)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("iExperiencedBreathingDifficulty")]
		public string IExperiencedBreathingDifficulty => this.Value<string>("iExperiencedBreathingDifficulty");

		///<summary>
		/// I experienced trembling: (eg, in the hands)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("iExperiencedTrembling")]
		public string IExperiencedTrembling => this.Value<string>("iExperiencedTrembling");

		///<summary>
		/// I felt down-hearted and blue
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("iFeltDownHeartedAndBlue")]
		public string IFeltDownHeartedAndBlue => this.Value<string>("iFeltDownHeartedAndBlue");

		///<summary>
		/// I felt I was close to panic
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("iFeltIWasCloseToPanic")]
		public string IFeltIwasCloseToPanic => this.Value<string>("iFeltIWasCloseToPanic");

		///<summary>
		/// I felt I wasn't worth much as a person
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("iFeltIWasnTWorthMuchAsAPerson")]
		public string IFeltIwasnTworthMuchAsAperson => this.Value<string>("iFeltIWasnTWorthMuchAsAPerson");

		///<summary>
		/// I felt scared without any good reason
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("iFeltScaredWithoutAnyGoodReason")]
		public string IFeltScaredWithoutAnyGoodReason => this.Value<string>("iFeltScaredWithoutAnyGoodReason");

		///<summary>
		/// I felt that I had nothing to look forward to
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("iFeltThatIHadNothingToLookForwardTo")]
		public string IFeltThatIhadNothingToLookForwardTo => this.Value<string>("iFeltThatIHadNothingToLookForwardTo");

		///<summary>
		/// I felt that I was rather touchy
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("iFeltThatIWasRatherTouchy")]
		public string IFeltThatIwasRatherTouchy => this.Value<string>("iFeltThatIWasRatherTouchy");

		///<summary>
		/// I felt that I was using a lot of nervous energy
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("iFeltThatIWasUsingALotOfNervousEnergy")]
		public string IFeltThatIwasUsingAlotOfNervousEnergy => this.Value<string>("iFeltThatIWasUsingALotOfNervousEnergy");

		///<summary>
		/// I felt that life was meaningless
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("iFeltThatLifeWasMeaningless")]
		public string IFeltThatLifeWasMeaningless => this.Value<string>("iFeltThatLifeWasMeaningless");

		///<summary>
		/// I found it difficult to relax
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("iFoundItDifficultToRelax")]
		public string IFoundItDifficultToRelax => this.Value<string>("iFoundItDifficultToRelax");

		///<summary>
		/// I found it difficult to work up the initiative to do things
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("iFoundItDifficultToWorkUpTheInitiativeToDoThings")]
		public string IFoundItDifficultToWorkUpTheInitiativeToDoThings => this.Value<string>("iFoundItDifficultToWorkUpTheInitiativeToDoThings");

		///<summary>
		/// I found it hard to wind down
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("iFoundItHardToWindDown")]
		public string IFoundItHardToWindDown => this.Value<string>("iFoundItHardToWindDown");

		///<summary>
		/// I found myself getting agitated
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("iFoundMyselfGettingAgitated")]
		public string IFoundMyselfGettingAgitated => this.Value<string>("iFoundMyselfGettingAgitated");

		///<summary>
		/// I tended to over-react to situations
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("iTendedToOverReactToSituations")]
		public string ITendedToOverReactToSituations => this.Value<string>("iTendedToOverReactToSituations");

		///<summary>
		/// I was aware of dryness of my mouth
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("iWasAwareOfDrynessOfMyMouth")]
		public string IWasAwareOfDrynessOfMyMouth => this.Value<string>("iWasAwareOfDrynessOfMyMouth");

		///<summary>
		/// I was aware of the action of my heart in the absence of physical exertion: (eg, sense of heart rate increase, heart missing a beat)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("iWasAwareOfTheActionOfMyHeartInTheAbsenceOfPhysicalExertion")]
		public string IWasAwareOfTheActionOfMyHeartInTheAbsenceOfPhysicalExertion => this.Value<string>("iWasAwareOfTheActionOfMyHeartInTheAbsenceOfPhysicalExertion");

		///<summary>
		/// I was intolerant of anything that kept me from getting on with what I was doing
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("iWasIntolerantOfAnythingThatKeptMeFromGettingOnWithWhatIWasDoing")]
		public string IWasIntolerantOfAnythingThatKeptMeFromGettingOnWithWhatIwasDoing => this.Value<string>("iWasIntolerantOfAnythingThatKeptMeFromGettingOnWithWhatIWasDoing");

		///<summary>
		/// I was unable to become enthusiastic about anything
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("iWasUnableToBecomeEnthusiasticAboutAnything")]
		public string IWasUnableToBecomeEnthusiasticAboutAnything => this.Value<string>("iWasUnableToBecomeEnthusiasticAboutAnything");

		///<summary>
		/// I was worried about situations in which I might panic and make a fool of myself
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("iWasWorriedAboutSituationsInWhichIMightPanicAndMakeAFoolOfMyself")]
		public string IWasWorriedAboutSituationsInWhichImightPanicAndMakeAfoolOfMyself => this.Value<string>("iWasWorriedAboutSituationsInWhichIMightPanicAndMakeAFoolOfMyself");

		///<summary>
		/// Patient Date Of Birth
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("patientDateOfBirth")]
		public DateTime PatientDateOfBirth => this.Value<DateTime>("patientDateOfBirth");

		///<summary>
		/// Patient Full Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("patientFullName")]
		public string PatientFullName => this.Value<string>("patientFullName");

		///<summary>
		/// Patient Surname
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("patientSurname")]
		public string PatientSurname => this.Value<string>("patientSurname");
	}
}
