//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Patients</summary>
	[PublishedModel("patients")]
	public partial class Patients : Master, IBanner
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "patients";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Patients, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public Patients(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Banner Video
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("bannerVideo")]
		public IPublishedContent BannerVideo => this.Value<IPublishedContent>("bannerVideo");

		///<summary>
		/// Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("eligibilityDescription")]
		public string EligibilityDescription => this.Value<string>("eligibilityDescription");

		///<summary>
		/// Eligibility form Button
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("eligibilityFormButton")]
		public Umbraco.Web.Models.Link EligibilityFormButton => this.Value<Umbraco.Web.Models.Link>("eligibilityFormButton");

		///<summary>
		/// Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("eligibilityHeading")]
		public string EligibilityHeading => this.Value<string>("eligibilityHeading");

		///<summary>
		/// Faq Button
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("faqButton")]
		public Umbraco.Web.Models.Link FaqButton => this.Value<Umbraco.Web.Models.Link>("faqButton");

		///<summary>
		/// Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("fAQHeading")]
		public string FAqheading => this.Value<string>("fAQHeading");

		///<summary>
		/// Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("howNCCHelpsDescription")]
		public IHtmlString HowNcchelpsDescription => this.Value<IHtmlString>("howNCCHelpsDescription");

		///<summary>
		/// Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("howNCCHelpsHeading")]
		public string HowNcchelpsHeading => this.Value<string>("howNCCHelpsHeading");

		///<summary>
		/// Ncc Commitments to patients
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("nccCommitmentsToPatients")]
		public IEnumerable<string> NccCommitmentsToPatients => this.Value<IEnumerable<string>>("nccCommitmentsToPatients");

		///<summary>
		/// Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("nccCommitmentsToPatientsHeading")]
		public string NccCommitmentsToPatientsHeading => this.Value<string>("nccCommitmentsToPatientsHeading");

		///<summary>
		/// Our Clinics Amenties
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ourClinicsAmenties")]
		public IEnumerable<ImageAndHeadingNC> OurClinicsAmenties => this.Value<IEnumerable<ImageAndHeadingNC>>("ourClinicsAmenties");

		///<summary>
		/// Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("ourClinicsAmentiesHeading")]
		public string OurClinicsAmentiesHeading => this.Value<string>("ourClinicsAmentiesHeading");

		///<summary>
		/// Patient registration Button
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("patientRegistrationButton")]
		public Umbraco.Web.Models.Link PatientRegistrationButton => this.Value<Umbraco.Web.Models.Link>("patientRegistrationButton");

		///<summary>
		/// Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("patientRegistrationDescription")]
		public string PatientRegistrationDescription => this.Value<string>("patientRegistrationDescription");

		///<summary>
		/// Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("patientRegistrationHeading")]
		public string PatientRegistrationHeading => this.Value<string>("patientRegistrationHeading");

		///<summary>
		/// Steps to get the treatment
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("stepsToGetTheTreatment")]
		public IEnumerable<ImageAndHeadingNC> StepsToGetTheTreatment => this.Value<IEnumerable<ImageAndHeadingNC>>("stepsToGetTheTreatment");

		///<summary>
		/// Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("stepsToGetTheTreatmentHeading")]
		public string StepsToGetTheTreatmentHeading => this.Value<string>("stepsToGetTheTreatmentHeading");

		///<summary>
		/// Banner Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("bannerDescription")]
		public IHtmlString BannerDescription => Banner.GetBannerDescription(this);

		///<summary>
		/// Banner heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("bannerHeading")]
		public string BannerHeading => Banner.GetBannerHeading(this);

		///<summary>
		/// Banner Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("bannerImage")]
		public IPublishedContent BannerImage => Banner.GetBannerImage(this);
	}
}
