//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Patient Information</summary>
	[PublishedModel("patientInformation")]
	public partial class PatientInformation : Master
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "patientInformation";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<PatientInformation, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public PatientInformation(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Accept NC Terms and Conditions
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("acceptNCTermsAndConditions")]
		public bool AcceptNctermsAndConditions => this.Value<bool>("acceptNCTermsAndConditions");

		///<summary>
		/// Date Of Birth
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("additionalInformationDateOfBirth")]
		public DateTime AdditionalInformationDateOfBirth => this.Value<DateTime>("additionalInformationDateOfBirth");

		///<summary>
		/// Decision Maker Date
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("additionalInformationDecisionMakerDate")]
		public DateTime AdditionalInformationDecisionMakerDate => this.Value<DateTime>("additionalInformationDecisionMakerDate");

		///<summary>
		/// Decision Maker Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("additionalInformationDecisionMakerName")]
		public string AdditionalInformationDecisionMakerName => this.Value<string>("additionalInformationDecisionMakerName");

		///<summary>
		/// Decision Maker Relation
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("additionalInformationDecisionMakerRelation")]
		public string AdditionalInformationDecisionMakerRelation => this.Value<string>("additionalInformationDecisionMakerRelation");

		///<summary>
		/// List Of All Current Medical And Specialist
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("additionalInformationListOfAllCurrentMedicalAndSpecialist")]
		public IEnumerable<AdditionalInformationListOfAllCurrentMedicalAndSpecialistNC> AdditionalInformationListOfAllCurrentMedicalAndSpecialist => this.Value<IEnumerable<AdditionalInformationListOfAllCurrentMedicalAndSpecialistNC>>("additionalInformationListOfAllCurrentMedicalAndSpecialist");

		///<summary>
		/// Patient Full Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("additionalInformationPatientFullName")]
		public string AdditionalInformationPatientFullName => this.Value<string>("additionalInformationPatientFullName");

		///<summary>
		/// Source Of Decision-Making Authority
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("additionalInformationSourceOfDecisionMakingAuthority")]
		public string AdditionalInformationSourceOfDecisionMakingAuthority => this.Value<string>("additionalInformationSourceOfDecisionMakingAuthority");

		///<summary>
		/// Witness
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("additionalInformationWitness")]
		public string AdditionalInformationWitness => this.Value<string>("additionalInformationWitness");

		///<summary>
		/// Witness Date
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("additionalInformationWitnessDate")]
		public DateTime AdditionalInformationWitnessDate => this.Value<DateTime>("additionalInformationWitnessDate");

		///<summary>
		/// Witness Relation
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("additionalInformationWitnessRelation")]
		public string AdditionalInformationWitnessRelation => this.Value<string>("additionalInformationWitnessRelation");

		///<summary>
		/// Agree to all National Canabinoid Clinic to acess your medical history records if needed.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("agreeToAllNationalCanabinoidClinicToAcessYourMedicalHistoryRecordsIfNeeded")]
		public bool AgreeToAllNationalCanabinoidClinicToAcessYourMedicalHistoryRecordsIfNeeded => this.Value<bool>("agreeToAllNationalCanabinoidClinicToAcessYourMedicalHistoryRecordsIfNeeded");

		///<summary>
		/// Aboriginal Or Torres  Strait Islander
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("patientSPersonalDetailsAboriginalOrTorresStraitIslander")]
		public bool PatientSpersonalDetailsAboriginalOrTorresStraitIslander => this.Value<bool>("patientSPersonalDetailsAboriginalOrTorresStraitIslander");

		///<summary>
		/// Address
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("patientSPersonalDetailsAddress")]
		public string PatientSpersonalDetailsAddress => this.Value<string>("patientSPersonalDetailsAddress");

		///<summary>
		/// Date Of Birth
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("patientSPersonalDetailsDateOfBirth")]
		public DateTime PatientSpersonalDetailsDateOfBirth => this.Value<DateTime>("patientSPersonalDetailsDateOfBirth");

		///<summary>
		/// DVA No.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("patientSPersonalDetailsDVANo")]
		public string PatientSpersonalDetailsDvano => this.Value<string>("patientSPersonalDetailsDVANo");

		///<summary>
		/// Email
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("patientSPersonalDetailsEmail")]
		public string PatientSpersonalDetailsEmail => this.Value<string>("patientSPersonalDetailsEmail");

		///<summary>
		/// Emergency Contacts Information
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("patientSPersonalDetailsEmergencyContactsInformation")]
		public IEnumerable<EmergencyContactInfoNC> PatientSpersonalDetailsEmergencyContactsInformation => this.Value<IEnumerable<EmergencyContactInfoNC>>("patientSPersonalDetailsEmergencyContactsInformation");

		///<summary>
		/// Employment Status
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("patientSPersonalDetailsEmploymentStatus")]
		public string PatientSpersonalDetailsEmploymentStatus => this.Value<string>("patientSPersonalDetailsEmploymentStatus");

		///<summary>
		/// Expiry Date
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("patientSPersonalDetailsExpiryDate")]
		public DateTime PatientSpersonalDetailsExpiryDate => this.Value<DateTime>("patientSPersonalDetailsExpiryDate");

		///<summary>
		/// Given Name(S)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("patientSPersonalDetailsGivenNameS")]
		public string PatientSpersonalDetailsGivenNameS => this.Value<string>("patientSPersonalDetailsGivenNameS");

		///<summary>
		/// Home Phone
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("patientSPersonalDetailsHomePhone")]
		public string PatientSpersonalDetailsHomePhone => this.Value<string>("patientSPersonalDetailsHomePhone");

		///<summary>
		/// If Other Than Language Well You Required A Certified Translator
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("patientSPersonalDetailsIfOtherThanLanguageWellYouRequiredACertifiedTranslator")]
		public string PatientSpersonalDetailsIfOtherThanLanguageWellYouRequiredAcertifiedTranslator => this.Value<string>("patientSPersonalDetailsIfOtherThanLanguageWellYouRequiredACertifiedTranslator");

		///<summary>
		/// Medicare Expiry
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("patientSPersonalDetailsMedicareExpiry")]
		public string PatientSpersonalDetailsMedicareExpiry => this.Value<string>("patientSPersonalDetailsMedicareExpiry");

		///<summary>
		/// Medicare Number
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("patientSPersonalDetailsMedicareNumber")]
		public string PatientSpersonalDetailsMedicareNumber => this.Value<string>("patientSPersonalDetailsMedicareNumber");

		///<summary>
		/// Mobile Number
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("patientSPersonalDetailsMobileNumber")]
		public string PatientSpersonalDetailsMobileNumber => this.Value<string>("patientSPersonalDetailsMobileNumber");

		///<summary>
		/// Native Language
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("patientSPersonalDetailsNativeLanguage")]
		public string PatientSpersonalDetailsNativeLanguage => this.Value<string>("patientSPersonalDetailsNativeLanguage");

		///<summary>
		/// Occupation
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("patientSPersonalDetailsOccupation")]
		public string PatientSpersonalDetailsOccupation => this.Value<string>("patientSPersonalDetailsOccupation");

		///<summary>
		/// Phone
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("patientSPersonalDetailsPhone")]
		public string PatientSpersonalDetailsPhone => this.Value<string>("patientSPersonalDetailsPhone");

		///<summary>
		/// Post Code
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("patientSPersonalDetailsPostCode")]
		public string PatientSpersonalDetailsPostCode => this.Value<string>("patientSPersonalDetailsPostCode");

		///<summary>
		/// Preferred Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("patientSPersonalDetailsPreferredName")]
		public string PatientSpersonalDetailsPreferredName => this.Value<string>("patientSPersonalDetailsPreferredName");

		///<summary>
		/// Ref. No.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("patientSPersonalDetailsRefNo")]
		public string PatientSpersonalDetailsRefNo => this.Value<string>("patientSPersonalDetailsRefNo");

		///<summary>
		/// State
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("patientSPersonalDetailsState")]
		public string PatientSpersonalDetailsState => this.Value<string>("patientSPersonalDetailsState");

		///<summary>
		/// Suburb
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("patientSPersonalDetailsSuburb")]
		public string PatientSpersonalDetailsSuburb => this.Value<string>("patientSPersonalDetailsSuburb");

		///<summary>
		/// Surname
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("patientSPersonalDetailsSurname")]
		public string PatientSpersonalDetailsSurname => this.Value<string>("patientSPersonalDetailsSurname");

		///<summary>
		/// Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("patientSPersonalDetailsTitle")]
		public string PatientSpersonalDetailsTitle => this.Value<string>("patientSPersonalDetailsTitle");

		///<summary>
		/// Work Email
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("patientSPersonalDetailsWorkEmail")]
		public string PatientSpersonalDetailsWorkEmail => this.Value<string>("patientSPersonalDetailsWorkEmail");

		///<summary>
		/// Work Phone
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("patientSPersonalDetailsWorkPhone")]
		public string PatientSpersonalDetailsWorkPhone => this.Value<string>("patientSPersonalDetailsWorkPhone");

		///<summary>
		/// Do You Currently Experience, Or Have A History Of, Any Of The Following Medical Condition?
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("personalMedicalHistoryDoYouCurrentlyExperienceOrHaveAHistoryOfAnyOfTheFollowingMedicalCondition")]
		public IEnumerable<TextNC> PersonalMedicalHistoryDoYouCurrentlyExperienceOrHaveAhistoryOfAnyOfTheFollowingMedicalCondition => this.Value<IEnumerable<TextNC>>("personalMedicalHistoryDoYouCurrentlyExperienceOrHaveAHistoryOfAnyOfTheFollowingMedicalCondition");

		///<summary>
		/// If Other
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("personalMedicalHistoryIfOther")]
		public string PersonalMedicalHistoryIfOther => this.Value<string>("personalMedicalHistoryIfOther");

		///<summary>
		/// List Of All Past Medications Taken For Your Conditions And The Length Of Time Taken Or Trailed
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("personalMedicalHistoryListOfAllPastMedicationsTakenForYourConditionsAndTheLengthOfTimeTakenOrTrailed")]
		public IEnumerable<PersonalMedicalHistoryAllPastMedicationsNC> PersonalMedicalHistoryListOfAllPastMedicationsTakenForYourConditionsAndTheLengthOfTimeTakenOrTrailed => this.Value<IEnumerable<PersonalMedicalHistoryAllPastMedicationsNC>>("personalMedicalHistoryListOfAllPastMedicationsTakenForYourConditionsAndTheLengthOfTimeTakenOrTrailed");

		///<summary>
		/// Potential Contraindications
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("personalMedicalHistoryPotentialContraindications")]
		public string PersonalMedicalHistoryPotentialContraindications => this.Value<string>("personalMedicalHistoryPotentialContraindications");

		///<summary>
		/// Understand that assessment by our doctors does not ensure approval and access to medical cannabis.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("understandThatAssessmentByOurDoctorsDoesNotEnsureApprovalAndAccessToMedicalCannabis")]
		public bool UnderstandThatAssessmentByOurDoctorsDoesNotEnsureApprovalAndAccessToMedicalCannabis => this.Value<bool>("understandThatAssessmentByOurDoctorsDoesNotEnsureApprovalAndAccessToMedicalCannabis");
	}
}
