//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Referral Form Information</summary>
	[PublishedModel("referralFormInformation")]
	public partial class ReferralFormInformation : Master
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "referralFormInformation";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ReferralFormInformation, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public ReferralFormInformation(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Address
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("address")]
		public string Address => this.Value<string>("address");

		///<summary>
		/// BY SUBMITTING THIS FORM
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("bYSUBMITTINGTHISFORM")]
		public IEnumerable<string> BYsubmittingthisform => this.Value<IEnumerable<string>>("bYSUBMITTINGTHISFORM");

		///<summary>
		/// Date of Birth
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("dateOfBirth")]
		public DateTime DateOfBirth => this.Value<DateTime>("dateOfBirth");

		///<summary>
		/// DOES THE PATIENT SUFFER FROM ANY OF THESE CONDITIONS?
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("dOESTHEPATIENTSUFFERFROMANYOFTHESECONDITIONS")]
		public IEnumerable<string> DOesthepatientsufferfromanyoftheseconditions => this.Value<IEnumerable<string>>("dOESTHEPATIENTSUFFERFROMANYOFTHESECONDITIONS");

		///<summary>
		/// DOES YOUR PATIENT HAVE A CURRENT CARE PLAN IN PLACE?
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("dOESYOURPATIENTHAVEACURRENTCAREPLANINPLACE")]
		public bool DOesyourpatienthaveacurrentcareplaninplace => this.Value<bool>("dOESYOURPATIENTHAVEACURRENTCAREPLANINPLACE");

		///<summary>
		/// Email
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("email")]
		public string Email => this.Value<string>("email");

		///<summary>
		/// First Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("firstName")]
		public string FirstName => this.Value<string>("firstName");

		///<summary>
		/// Gender
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("gender")]
		public string Gender => this.Value<string>("gender");

		///<summary>
		/// IF OTHER, PLEASE SPECIFY..
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("iFOTHERPLEASESPECIFY")]
		public string IFotherpleasespecify => this.Value<string>("iFOTHERPLEASESPECIFY");

		///<summary>
		/// IF YOUR PATIENT DOES NOT HAVE A CURRENT CARE PLAN IN PLACE WOULD YOU CONSENT FOR OUR NCC DOCTOR TO INITIATE ONE?
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("iFYOURPATIENTDOESNOTHAVEACURRENTCAREPLANINPLACEWOULDYOUCONSENTFOROURNCCDOCTORTOINITIATEONE")]
		public bool IFyourpatientdoesnothaveacurrentcareplaninplacewouldyouconsentforournccdoctortoinitiateone => this.Value<bool>("iFYOURPATIENTDOESNOTHAVEACURRENTCAREPLANINPLACEWOULDYOUCONSENTFOROURNCCDOCTORTOINITIATEONE");

		///<summary>
		/// Last Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("lastName")]
		public string LastName => this.Value<string>("lastName");

		///<summary>
		/// Medicare Expiry
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("medicareExpiry")]
		public string MedicareExpiry => this.Value<string>("medicareExpiry");

		///<summary>
		/// Medicare Number
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("medicareNumber")]
		public string MedicareNumber => this.Value<string>("medicareNumber");

		///<summary>
		/// Phone
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("phone")]
		public string Phone => this.Value<string>("phone");

		///<summary>
		/// PLEASE LIST ALL PAST MEDICATIONS FOR THE PATIENT AND THE LENGTH TRIED:
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("pLEASELISTALLPASTMEDICATIONSFORTHEPATIENTANDTHELENGTHTRIED")]
		public string PLeaselistallpastmedicationsforthepatientandthelengthtried => this.Value<string>("pLEASELISTALLPASTMEDICATIONSFORTHEPATIENTANDTHELENGTHTRIED");

		///<summary>
		/// Postcode
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("postcode")]
		public string Postcode => this.Value<string>("postcode");

		///<summary>
		/// Address
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("practitionerDetailsAddress")]
		public string PractitionerDetailsAddress => this.Value<string>("practitionerDetailsAddress");

		///<summary>
		/// Email
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("practitionerDetailsEmail")]
		public string PractitionerDetailsEmail => this.Value<string>("practitionerDetailsEmail");

		///<summary>
		/// Full Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("practitionerDetailsFullName")]
		public string PractitionerDetailsFullName => this.Value<string>("practitionerDetailsFullName");

		///<summary>
		/// HealthLink Number
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("practitionerDetailsHealthLinkNumber")]
		public string PractitionerDetailsHealthLinkNumber => this.Value<string>("practitionerDetailsHealthLinkNumber");

		///<summary>
		/// Phone Number
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("practitionerDetailsPhoneNumber")]
		public string PractitionerDetailsPhoneNumber => this.Value<string>("practitionerDetailsPhoneNumber");

		///<summary>
		/// Practitioner Type
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("practitionerDetailsPractitionerType")]
		public string PractitionerDetailsPractitionerType => this.Value<string>("practitionerDetailsPractitionerType");

		///<summary>
		/// Provider Number
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("practitionerDetailsProviderNumber")]
		public string PractitionerDetailsProviderNumber => this.Value<string>("practitionerDetailsProviderNumber");

		///<summary>
		/// REASON FOR REFERRAL
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("rEASONFORREFERRAL")]
		public string REasonforreferral => this.Value<string>("rEASONFORREFERRAL");

		///<summary>
		/// Referral Date
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("referralDate")]
		public DateTime ReferralDate => this.Value<DateTime>("referralDate");

		///<summary>
		/// Ref No.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("refNo")]
		public string RefNo => this.Value<string>("refNo");

		///<summary>
		/// State
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("state")]
		public string State => this.Value<string>("state");

		///<summary>
		/// Suburb
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("suburb")]
		public string Suburb => this.Value<string>("suburb");

		///<summary>
		/// TITLE
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("tITLE")]
		public string TItle => this.Value<string>("tITLE");

		///<summary>
		/// WOULD YOU LIKE US TO DO A CARE PLAN REVIEW FOR YOUR PATIENT?
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("wOULDYOULIKEUSTODOACAREPLANREVIEWFORYOURPATIENT")]
		public bool WOuldyoulikeustodoacareplanreviewforyourpatient => this.Value<bool>("wOULDYOULIKEUSTODOACAREPLANREVIEWFORYOURPATIENT");
	}
}
